# Generated by Django 5.2.4 on 2025-07-25 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('cost_per_token', models.DecimalField(decimal_places=2, help_text='Cost per $NUC token investment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
    ]
