# Generated by Django 5.2.4 on 2026-01-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address (0x...) for blockchain interactions', max_length=42, null=True, unique=True),
        ),
    ]
