# Generated by Django 5.2.4 on 2025-07-30 04:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(choices=[('nuwave', 'NuWave'), ('phoenix_regenx7', 'Phoenix RegenX-7'), ('nexus_core', 'Nexus CORE'), ('fermi_iii', 'Fermi-III'), ('helios_fusiondrive', 'Helios FusionDrive')], max_length=50, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('annual_roi_rate', models.DecimalField(decimal_places=4, help_text='Annual ROI as decimal, can be negative (ex: 0.0650 = 6.5%)', max_digits=6)),
                ('carbon_offset_tonnes_co2_per_nuc_per_year', models.DecimalField(decimal_places=4, help_text='Tonnes of CO₂ offset per $NUC invested per year', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_funding_needed', models.DecimalField(decimal_places=2, help_text='Total $NUC needed to fully fund this reactor', max_digits=15)),
                ('current_funding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total $NUC currently invested in this reactor', max_digits=15)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nuclear Reactor',
                'verbose_name_plural': 'Nuclear Reactors',
                'ordering': ['name'],
            },
        ),
    ]
