# Generated by Django 5.2.4 on 2025-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactors', '0002_remove_reactor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='slug',
            field=models.CharField(choices=[('nuwave', 'NuWave'), ('phoenix_regenx7', 'Phoenix RegenX-7'), ('nexus_core', 'Nexus CORE'), ('fermi_iii', 'Fermi-III'), ('helios_fusiondrive', 'Helios FusionDrive'), ('atucha_qtronix', 'Atucha Q-Tronix')], max_length=50, unique=True),
        ),
    ]
