# Generated by Django 5.2.4 on 2025-07-30 04:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reactors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, help_text='Amount of $NUC invested in this reactor', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('time_period_years', models.PositiveIntegerField(help_text='Investment time period in years (1, 2, 5, or 10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='reactors.reactor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
